di-sukharev/opencommit

src/api.ts

Axios provides a util function called `isAxiosError` which can detect the shape of your error. By using it, we can avoid the [type assertion](https://typescript.tv/glossary/#Type-Assertion) of `error as AxiosError`. 
The error handling code will be now more type-safe since we no longer have to use the `any` type for the error variable (see [better error handling with unknown type](https://www.youtube.com/watch?v=xdQkEn3mx1k)).

Replace type assertion with built-in error detection

---

src/commands/config.ts
src/generateCommitMessageFromGitDiff.ts
src/i18n/de.json
src/i18n/en.json
src/i18n/fr.json
src/i18n/index.ts
src/i18n/it.json
src/i18n/ja.json
src/i18n/ko.json
src/i18n/zh_CN.json
src/i18n/zh_TW.json

feat(i18n): add translations in Italian, Japanese, Korean, Simplified Chinese, Traditional Chinese, French, and German

🚀  i18n: add internationalization support

---

README.md
src/cli.ts
src/commands/commit.ts

As the name of the PR explains I added a few lines to support some extra arguments to be passed to the `git commit` command.
For example, say I want to execute git commit with `--no-verify` using oc I simply cannot do it,
What I added makes you able to do `oc --no-verify` and it  translates to `git commit -m ${generatedText} --no-verify`

feat: Add support for extra args to be passed to the git commit command

---

src/utils/git.ts

The relative flag has been added to the git diff command in the getStagedFiles function. This flag makes the output of the command relative to the current working directory, which makes it easier to work with the file paths and enables executing opencommit from anywhere in the repository, not just from the root.

fix(git.ts): add relative flag to git diff command

---

package-lock.json
package.json
src/api.ts
src/cli.ts
src/utils/checkIsLatestVersion.ts

feature request: telling user when new version is available

---

src/utils/git.ts

Following #37 and #38 the function getStagedFiles has been refactored to use git rev-parse to get the root directory of the repository. This improves the reliability of the function as it will work regardless of the current working directory. The root directory is then passed to the git diff command to get the list of staged files. With only the --relative flag, as I have done in #37, staged diff(s) on files in a different same level directory as the current working one would not be found by the command.

refactor(git.ts): use git rev-parse to get the root directory of the repo

---

src/commands/githook.ts

The import statement for the fileURLToPath function from the url module is not used in the file. Therefore, it has been removed to improve code readability and maintainability.

🔥 refactor(githook.ts): remove unused import

---

package-lock.json
src/commands/githook.ts

The `SYMLINK_URL` has been updated to fix an issue with the CLI tool that caused it to crash on Windows environments with the error message "SystemError [ERR_TTY_INIT_FAILED]: TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)".

fix(githook.ts): fix SYMLINK_URL for Windows

---

esbuild.config.js
package.json
src/utils/tokenCount.ts

Reference to https://github.com/di-sukharev/opencommit/pull/63#issuecomment-1487894924
When esbuild the cli.cjs, it doesn't include the WebAssembly file. Is it possible copy the wasm file to out folder to solve the error?

Copy wasm file to out folder to solve the file not found error

---

src/commands/config.ts

The error message for the OPENAI_BASE_PATH validation has been updated to be more descriptive and helpful. The message now reads "Must be string" instead of "${value} is not supported yet". This change improves the clarity of the error message and makes it easier for developers to understand what went wrong when the validation fails.
#163 fixing

🐛 fix(config.ts): error message for OPENAI_BASE_PATH validation

---

src/commands/commit.ts
src/commands/config.ts
src/generateCommitMessageFromGitDiff.ts

- Set default values for OCO_MODEL and OCO_LANGUAGE when reading from environment variables
- Remove unused GenerateCommitMessageError interface

fix(config.ts): handle undefined values and improve validation for `OCO_OPENAI_MAX_TOKENS` and `OCO_MODEL`

---

.prettierrc
out/cli.cjs
package-lock.json
package.json
src/api.ts
src/commands/config.ts
src/generateCommitMessageFromGitDiff.ts

feat(generateCommitMessageFromGitDiff.ts): changing logic of MAX_REQ_TOKENS
fix(api.ts): add missing import for GenerateCommitMessageErrorEnum The token count validation is added to prevent the request from exceeding the default model token limit. The validation is done by counting the tokens in each message and adding 4 to each count to account for the additional tokens added by the API. If the total token count exceeds the limit, an error is thrown. The missing import for GenerateCommitMessageErrorEnum is also added.
feat: add support for splitting long line-diffs into smaller pieces This change adds support for splitting long line-diffs into smaller pieces to avoid exceeding the maximum commit message length. The `splitDiff` function splits a single line into multiple lines if it …

feat(api.ts): solving bad request issue

---

README.md

This is an identical pull request to #190 without the lots of changes issue. This should be okay to merge.
This commit addresses grammatical errors found in the project's readme and improves its overall grammar.
Emphasizing the significance of proper grammar cannot be stressed enough when it comes to enhancing the presentation of a project. Today, I came across this GitHub repository in a news article and was intrigued by the concept. Therefore, I decided to explore the repository. To my disappointment, I discovered several grammatical errors in the README.md file. However, the advantage of open source is that I can rectify these errors myself relatively easily if they bother me.
Please inform me if any modifications are necessary.

Re #190 - Fixing grammatical errors and enhancing overall grammar in README.md

---

src/commands/config.ts

In my company we use dedicated proxy server for OpenAI API requests, so my API KEY has shorter length that validation allows. This fix allow any length of OCO_OPENAI_API_KEY if OCO_OPENAI_BASE_PATH key is set to other value

Allow any leght of OCO_OPENAI_API_KEY when OCO_OPENAI_BASE_PATH value is set

---

src/modules/commitlint/config.ts
src/modules/commitlint/utils.ts

Sometimes GPT responds with additional text before surfacing the JSON block. 
It is also worth noting that the config is still subject to `OCO_OPENAI_MAX_TOKENS` rules which may also cause the result to be truncated. Most likely we should be ignoring the MAX_TOKEN limit when fetching the config.

Bug (commitling) Parse JSON blocks from return response

---

src/commands/commit.ts

commit.ts : Remove messageTemplate from extraArgs to prevent git Error to fix this bug : 
https://github.com/di-sukharev/opencommit/issues/278
extraArgs contains all git extra flag but also the user custom message when use $msg.
For exemple oco '#11 $msg' return a bad git command
`git commit -m #11 generated_message #11 $msg`
This fix change remove the template message from extraArgs to generate this correct command : 
`git commit -m #11 generated_message`

(fix commit.ts) Remove messageTemplate from extraArgs to prevent git Error

---

README.md
src/commands/config.ts

I have updated the list of models that can be set as OCO_MODEL within OpenCommit to include the latest versions, while removing the legacy GPT-3.5 Turbo models as outlined in [the OpenAI official documentation](https://platform.openai.com/docs/models/gpt-3-5-turbo).
- Updating the list of eligible models for setting as OCO_MODEL to include the most recent versions.
- Changing the default value of OCO_MODEL to the most recent and optimized model version.
- Removing legacy GPT-3.5 Turbo models from the list and conducting a cleanup of related code.

Feat: Update OCO_MODEL to Latest Version and Remove Legacy GPT-3.5 Turbo Models

---

README.md
src/commands/config.ts
src/modules/commitlint/prompts.ts
src/prompts.ts

- Introduce OCO_ONE_LINE_COMMIT option to enable crafting of concise, unified commit messages.
- Update README.md, config.ts, and prompts in commitlint and main prompts to support and validate the new configuration.
- Extend AI provider options with 'gpt-4-0125-preview'.

feat: add OCO_ONE_LINE_COMMIT config for concise commit messages

---

src/cli.ts

This PR is for fixing the bug with the 'fgm' flag.
When executing the ```oco``` command using the ```--fgm``` flag, the value of the ```fgm``` flag is not correctly reflected. Instead, ```isStageAllFlag``` is mistakenly treated as true.
This is because, in the following commit, the order of arguments in the 'commit' function changed, but this was not reflected in the arguments at the call site.
https://github.com/di-sukharev/opencommit/commit/a33027b4db60bf7d16fc3e794e2a3e4cbc540330
```javascript
// File: commands/commit.ts
export async function commit(
extraArgs: string[] = [],
isStageAllFlag: Boolean = false,
fullGitMojiSpec: boolean = false
) {
if (isStageAllFlag) {
...
}
// File: cli.ts
commit(extraArgs, flags.fgm); // The value of 'flags.fgm' is being passed to 'isStageAllFlag'
```
* …

🐛 bug fix(cli.ts): properly handle the 'fgm' flag argument.

---

out/cli.cjs
package-lock.json
package.json

Feature Request : #289
When making multiple commits it is time-consuming to skip the "Do you want to run git push?" question each time.
I can assume people (and I) don't want to make a push for each separate commit.
have a `oco config set OCO_ASK_GIT_PUSH=true` or `oco config set OCO_ASK_GIT_PUSH=false` (`true` by default)
- show the "Do you want to run git push?" on `true`
- don't show on `false`

feat: #289 - Add possibility to skip git push question by setting `OCO_ASK_GIT_PUSH` config var

---

out/cli.cjs
out/github-action.cjs
test/e2e/oneFile.test.ts

I have fixed the E2E tests that were broken in recent commits.
The flow of asking about ```git push``` after commit has been changed with the addition of ```OCO_GITPUSH``` in the following PR: https://github.com/di-sukharev/opencommit/pull/220
I have updated the expected values of the E2E tests to align with the latest flow.
- ```npm run test:e2e:docker``` (recommended)
- ```npm run test:e2e``` (caution required for execution)
- **It doesn't work if there is a global configuration file** (~/.opencommit)
- There is a bug in the getConfig method. If a global configuration file exists, it does not return default settings for keys not listed in the configuration file. As a result, the flow of this ```git push``` changes and E2E test failed.

✅ fix the broken E2E tests due to the addition of OCO_GITPUSH

---

out/cli.cjs
out/github-action.cjs
package.json
src/commands/config.ts

This PR is a bug fix for Issue #326
OpenAI has introduced a new API key format:
* New format for project API keys
- sk-proj-xxxx....xxxx (56 characters in length)
* Old format for API keys
- sk-xxxx...xxxx (51 characters in length)
When trying to use the new project API key, a validation error occurs due to the API key format check, which currently only accepts keys of 51 characters in length.
Remove the validation related to the length of the API key.

🐛bug fix: enable to use the new format of OpenAI's project API Key

---

README.md

This pull request corrects a typographical error in the configuration command from `oc` to `oco`.
The original command contained a typo:
```sh
oc config set OCO_GITPUSH=false
```
The correct command should use `oco` instead of `oc`:
```sh
oco config set OCO_GITPUSH=false
```

docs: Corrected a Typographical Error in Configuration Command

---

README.md
src/cli.ts
src/commands/commit.ts

- Add `--yes, -y` flag to skip commit confirmation prompt.
- Document the `--yes` flag usage in README for user guidance.

Feature: Add command line flag --yes, -y to skip commit confirmation

---

package.json
src/commands/config.ts
src/engine/testAi.ts
src/modules/commitlint/config.ts
src/modules/commitlint/pwd-commitlint.ts
src/modules/commitlint/utils.ts
test/e2e/prompt-module/commitlint.test.ts
test/e2e/prompt-module/data/commitlint_18/commitlint.config.js
test/e2e/prompt-module/data/commitlint_18/package-lock.json
test/e2e/prompt-module/data/commitlint_18/package.json
test/e2e/prompt-module/data/commitlint_19/commitlint.config.js
test/e2e/prompt-module/data/commitlint_19/package-lock.json
test/e2e/prompt-module/data/commitlint_19/package.json
test/e2e/prompt-module/data/commitlint_9/commitlint.config.js
test/e2e/prompt-module/data/commitlint_9/package-lock.json
test/e2e/prompt-module/data/commitlint_9/package.json
test/e2e/setup.sh
test/e2e/utils.ts

* The `OCO_PROMPT_MODULE=@commitlint` functionality is currently not working as expected. The following steps reproduce the issue:
- Run `npm i @commitlint/cli`
- Create `commitlint.config.js`
- Set `OCO_PROMPT_MODULE=@commitlint`
- run `oco commitlint force`
- => An error occurs
* There's a bug in `src/modules/commitlint/utils.ts#getJSONBlock`
- `consistency` is not defined (a misspelling of `input`).
* The method `src/modules/commitlint/pwd-commitlint.ts#getCommitLintPWDConfig` only supports the CJS version of the `@commitlint/load` package.
- This method calls the `@commitlint/load` package using `require`. However, commitlint v19 and onwards only support pure ESM.
* Fix the `OCO_PROMPT_MODULE=@commitlint` functionality
- by correcting the bug in …

🐛Fix: prompt-module/@commitlint

---

out/cli.cjs
out/github-action.cjs
src/commands/config.ts

Resolving #352 setting initial value of OCO_AZURE_ENDPOINT to undefined instead of '', where it causes errors while trying to set any other config upon initial installation.

fix(config.ts): invalid default config

---

package-lock.json

When running `npm ci` on the dev branch, the following error occurs.
```
`npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```
We need to run `npm install` to sync package.json and package-lock.json.
I updated package-lock.json by running `npm install`

Fix: resolve error on 'npm ci' by running 'npm install'

---

test/unit/utils.ts

Fixed so that it does not cause an error when the cleanup function is executed for a directory that no longer exists.

Fix: cleanup function

---

out/cli.cjs
out/github-action.cjs
src/commands/commit.ts
src/commands/config.ts
test/unit/config.test.ts
test/unit/utils.ts
tsconfig.json

solve https://github.com/di-sukharev/opencommit/issues/390 and refactor isCancel

390 add config set tests

---

src/engine/ollama.ts

It looks like #391 refactoring broke ollama, using opencommit 3.1.1 with `OCO_AI_PROVIDER=ollama` will fail to connect displaying the following error:
```
┌  opencommit
│
○  Generating commit message
│
└  ✖ Error: Ollama provider error: Invalid URL
```

🔧 Fixes regression introduced in ollama engine 

---

README.md
src/commands/commit.ts
test/e2e/gitPush.test.ts
test/e2e/oneFile.test.ts
test/e2e/prompt-module/commitlint.test.ts
test/e2e/utils.ts

If git remote is not set, `oco` needs to skip the `git push` process regardless the `OCO_GITPUSH` setting.
* When git remote does not exist, return early.
* Add E2E tests related to git remote (each pattern: no remote / only one remote / two remotes)

Fix: a bug that causes an error when pushing without setting git remote

---

README.md
out/cli.cjs
out/github-action.cjs
package-lock.json
package.json
src/cli.ts
src/commands/commit.ts
src/commands/config.ts
src/commands/prepare-commit-msg-hook.ts
src/engine/flowise.ts
src/engine/gemini.ts
src/engine/ollama.ts
src/generateCommitMessageFromGitDiff.ts
src/migrations/00_use_single_api_key_and_url.ts
src/migrations/01_remove_obsolete_config_keys_from_global_file.ts
src/migrations/02_set_missing_default_values.ts
src/migrations/_migrations.ts
src/migrations/_run.ts
src/utils/engine.ts
test/unit/config.test.ts
test/unit/gemini.test.ts

migrates all API_KEYs configs (e.g. OCO_OPENAI_API_KEY, OCO_GEMINI_API_KEY) to a single OCO_API_KEY config — to make it simpler to support.
same for OCO_ENDPOINT_URLs and OCO_API_URLs, there were a bunch, now it's all a single OCO_API_URL.
migrations should manage changing old keys to new keys automatically.

refactoring v2

---

src/commands/config.ts
src/engine/groq.ts
src/engine/openAi.ts
src/utils/engine.ts

Following comments in #346, I set up groq support with the `OCO_GROQ_API_KEY` variable by setting the OCO_AI_PROVIDER to groq.
I am not very familiar with this project, so please feel free to point out mistakes.

Add Groq AI support.

---

out/cli.cjs
out/github-action.cjs
src/commands/commit.ts
src/commands/config.ts
src/migrations/02_set_missing_default_values.ts
src/migrations/_run.ts

3.2.2 introduced a bug with migrations described here https://github.com/di-sukharev/opencommit/pull/412#issuecomment-2334427947
this pr fixes it

fix migrations

---

src/commands/commit.ts

When you run 'oco' command and commit, you will be asked which remote to push to if there are multiple remotes.
Currently, you have to force quit by Ctrl-C if you don't want to push.
I have improved usability by adding an option to `Don't push`.
Added `Don't push` as an option in the git push flow when there are multiple remotes.
**Before:**
**After:**

Feat: Add an option to `Don't push` when there are multiple git remotes

---

.github/CONTRIBUTING.md
out/cli.cjs
out/github-action.cjs
package-lock.json
package.json
src/commands/config.ts
src/engine/mlx.ts
src/utils/engine.ts

feat(engine): add support for MLX AI provider

feat(engine): add support for MLX AI provider

---

src/engine/ollama.ts

Hello,
When utilizing the DeepSeek model via Ollama, responses generated by the reasoning model include reflective content encapsulated within <think> and </think> tags. 
This additional information is intended for internal reasoning processes and is not suitable for commit messages. To ensure that only the conventional commit message is retained, it is necessary to remove any content enclosed within these tags.
I did this only for ollama, maybe it would be better to add an option to remove this kind of tag globally.

Enhance OllamaEngine to remove <think> blocks in response content

---

README.md
src/commands/config.ts
src/engine/deepseek.ts
src/utils/engine.ts

#443
Added DeepSeek model support. Since I'm new to this project, please feel free to point out any issues. Context caching for DeepSeek (as discussed in https://github.com/di-sukharev/opencommit/issues/443#issuecomment-2621731786) is not implemented yet.

Add deepseek support

---

src/modules/commitlint/pwd-commitlint.ts

This change allows opencommit to locate commitlint installed globally (with opencommit), which is useful for project that does not use node.js environment or dose not install opencommit and @commitlint locally.

feat(commitlint): add additional search path for @commitlint

---

src/commands/config.ts

The defaults in the README.md do not match the config file, tweaked it to match the configuration described in the README.md (the it should be the opposite, either way it must match)

fix: config default settings

---

src/prompts.ts

This update introduces a new structure for generating commit messages by defining a constant for commit types and consolidating the logic into a single function. The changes enhance readability and maintainability while ensuring consistent formatting based on the OCO_OMIT_SCOPE configuration.
-----
This merge request is the first of five commits intended to archive `feat(commitlint): Improve consistency handling and prompt structure`. I have split the changes into five reviewable merge requests that will be submitted sequentially.
-----
feat(commitlint): Improve consistency handling and prompt structure
-----
Problem:
The current commitlint integration has limitations in generating commit messages that strictly follow commitlint rules. For example, when commitlint config has …

refactor(prompts): streamline commit message generation logic

---

.gitignore
jest.config.ts
package-lock.json
package.json
src/modules/commitlint/config.ts
src/modules/commitlint/prompts.ts
src/modules/commitlint/pwd-commitlint.ts
src/utils/removeContentTags.ts
test/jest-setup.ts

The commitlint configuration and prompts have been refactored to enhance clarity and maintain consistency throughout the codebase. The type assertion for commitLintConfig is updated to use 'as any' for better type handling. Additionally, formatting adjustments are made in the prompts to ensure proper readability and alignment with the defined conventions. These changes aim to streamline the commit message generation process and improve overall code maintainability.
-----
This merge request is the 2nd of 5 commits intended to archive `feat(commitlint): Improve consistency handling and prompt structure`. I have split the changes into five reviewable merge requests that will be submitted sequentially.
Problem:
The current commitlint integration has limitations in generating commit messages …

refactor(commitlint): update commitlint configuration and prompts

---

README.md
src/commands/config.ts
src/engine/Engine.ts
src/engine/ollama.ts
src/engine/openAi.ts
src/utils/engine.ts
test/unit/config.test.ts

This pull request implements the feature described in #466 by adding support for custom HTTP headers in API requests via the new `OCO_API_CUSTOM_HEADERS` configuration option.
- Introduces the `OCO_API_CUSTOM_HEADERS` environment/config variable.
- Allows users to set custom HTTP headers (as a JSON object) for all API requests, supporting use cases like custom authentication, corporate proxy headers, and API gateway requirements.
```sh
oco config set OCO_API_CUSTOM_HEADERS='{"Authorization": "Basic dXNlcm5hbWU6cGFzc3dvcmQ="}'
oco config set OCO_API_CUSTOM_HEADERS='{"X-API-Version": "2", "X-Custom-Header": "value"}'
```
Close #466

Add OCO_API_CUSTOM_HEADERS

---

README.md
src/commands/config.ts

This commit adds a new 'describe' mode to the config command, allowing users to get detailed information about configuration parameters. It includes:
1. New CONFIG_MODES.describe enum value
2. Functions to generate and print help messages for config parameters
3. Updated configCommand to handle the new 'describe' mode
4. README updates to document the new 'describe' functionality
The `describe` mode can be used in two ways:
1. To print help for all available config parameters: ``` oco config describe ```
2. To print help for specific config parameters: ``` oco config describe OCO_MODEL OCO_API_KEY ```
Additionally, the commit fixes the error handling for the `get` and `set` modes, ensuring that an error is thrown if no config keys are provided.
These changes improve the usability and …

feat(config): add 'describe' mode to config command for detailed parameter info

---

src/prompts.ts

When user wanted a one line commit the system prompt and the user/assistant one-shot example were contradicting each other, confusing the LLM. This fix modifies the assistant output so that prompt and one-shot are consistent.
see [Issue #469](https://github.com/di-sukharev/opencommit/issues/469#issuecomment-2848916971)
```
OCO_ONE_LINE_COMMIT=true OCO_DESCRIPTION=false oco
```
```
└  Generated commit message:
——————————————————
feat(algo_2.py): replace hardcoded debug_stop value with environment variable for better configurability 
feat(buffers.py): add BufferVal class to encapsulate value and timestamp for improved data handling
```
```
OCO_ONE_LINE_COMMIT=true OCO_DESCRIPTION=true oco
```
```
└  Generated commit message:
——————————————————
feat(algo_2.py): replace hardcoded debug_stop …
```

fix(prompts.ts): edited contradictory assistant output

---

src/cli.ts

Thank you for such a great tool😀
I noticed that the `--fgm` option in the `oco` command help output does not have a description:
The motivation of this pull request is to improve the clarity of the help message by adding a description for the `--fgm` flag.
```sh
$ oco -h
opencommit v3.2.7
Auto-generate impressive commits in 1 second. Killing lame commits with AI 🤯🔫
Usage:
opencommit [flags...]
opencommit <command>
Commands:
config
hook
commitlint
Flags:
-c, --context <string>        Additional user input context for the commit message
--fgm
-h, --help                    Show help
--version                 Show version
-y, --yes                     Skip commit confirmation prompt
```
```sh
$ oco -h  
opencommit v3.2.7
Auto-generate impressive commits in 1 second. Killing lame commits with …
```

feat(cli.ts): enhance fgm flag to include description and default value for better usability

---

src/commands/config.ts
src/engine/openrouter.ts
src/utils/engine.ts

This PR introduces **OpenRouter** as a new AI provider, granting access to over 300 diverse AI models through a unified API. This integration significantly expands the range of models available for generating commit messages.
- **Implemented OpenRouter Engine (`src/engine/openrouter.ts`)**
- Created a new `OpenRouterEngine` class to communicate with the OpenRouter API.
- It handles authentication using an API key and sends requests with the appropriate headers (`HTTP-Referer`, `X-Title`).
- Implemented error handling, which now clearly displays error messages from OpenRouter, especially for authentication failures (401).
- **Updated Configuration (`src/commands/config.ts`)**
- Added `OPENROUTER` to the `OCO_AI_PROVIDER_ENUM`, making it a selectable provider.
- Included a comprehensive …

✨ add openrouter AI provider support with comprehensive model list

---

src/commands/prepare-commit-msg-hook.ts

According to the discussion at https://github.com/di-sukharev/opencommit/issues/490, modify the `git commit` template during the hook to the default comment stats to align with general `git commit` practices.

feat(prepare-commit-msg-hook): enhance commit message formatting with a divider and instructions for better user guidance

---

src/commands/commit.ts

Add an option to let users edit the commit message before committing.
- https://github.com/di-sukharev/opencommit/issues/250
- https://github.com/di-sukharev/opencommit/issues/169
- https://github.com/di-sukharev/opencommit/issues/81
- https://github.com/di-sukharev/opencommit/issues/53
- https://github.com/di-sukharev/opencommit/pull/179

feat(commit.ts): enable users to edit commit message before committing

---

src/commands/commit.ts

This PR resolves a TypeScript error in `commit.ts` caused by a missing `confirm` import and incorrect usage of the `text()` prompt. Specifically:
- Adds the missing `confirm` import from the prompt toolkit
- Corrects usage of `text()` by storing the result in a `textResponse` variable and converting it to a string before assigning it to `commitMessage`
These changes fix the build error introduced in #491 and restore proper interactive behavior during the commit flow.

Fix TypeScript build error and add missing confirm import (regression from #491)
