README.md
package-lock.json
package.json
src/commands/commit.ts
src/commands/prepare-commit-msg-hook.ts
src/utils/git.ts
src/utils/trytm.ts

* feat: add staged files multiple selection (#6)

Feature: add staged files multiple selection (#6)

---

src/generateCommitMessageFromGitDiff.ts

Remove unnecessary } at the end of the line.
This change do not affect normal functionality.

Fix(generateCommitMessageFromGitDiff.ts): remove unnecessary characte

---

src/i18n/es_ES.json
src/i18n/index.ts

- Issue: https://github.com/di-sukharev/opencommit/issues/57
@di-sukharev Let me know and i'll make any changes.

[FEAT](i18n): Add support for Spanish  language (es_ES).

---

src/i18n/index.ts
src/i18n/vi_VN.json

- feat(i18n): add translation in Vietnamese
@di-sukharev  Feel free to make any changes.

feat(i18n): add support for Vietnamese (Vietnam) language (vi_VN)

---

package-lock.json
package.json
src/commands/githook.ts
src/i18n/index.ts
src/i18n/pl.json

- feat(i18n): add Polish translation file A new translation file for the Polish language has been added to the project. It includes translations for the commit messages in the conventional commit convention.
- feat(i18n): add support for Polish language The Polish language is now supported in the application. A new JSON file, pl.json, has been added to the i18n directory. The new file contains translations for the commit messages in Polish. The I18nLocals enum has been updated to include the new language, and the i18n object has been updated to include the new translations. The getI18nLocal function has also been updated to recognize the new language.

feat(i18n): add support for Polish language

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/featureRequest.yaml

We should add issue templates to the project. Some bugs being reported are not descriptive enough to help. Also added a feature request template as well to get new ideas more articulated.

Issue templates

---

src/api.ts
src/commands/config.ts

feat(config.ts): add OPENAI_BASE_PATH configuration key and validator function

feat(api.ts): add support for OPENAI_BASE_PATH configuration variable

---

.prettierrc
src/commands/commit.ts

Reverts di-sukharev/opencommit#70
fails for me on latest macos with:
```
└  ✖ Error: Command failed with exit code 1: open  vi tmp_commit.txt
The file /Users/dima.sukharev/Desktop/repositories/sukharev/opencommit/vi does not exist.
```

Revert "Suggest adding 'Edit' option to the Yes/No confirmation #53"

---

README.md
out/cli.cjs
package-lock.json
package.json
src/api.ts
src/commands/commit.ts
src/commands/prepare-commit-msg-hook.ts

`oc` is a pretty well-known alias for OpenShift CLI
Closes https://github.com/di-sukharev/opencommit/issues/144

Remove oc alias

---

README.md

This PR updates the `README.md` file to provide a comprehensive explanation of the `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` feature in the `opencommit` tool.
- **Overview**: A brief introduction to the `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` feature and its significance.
- **Implementation Details**: A deep dive into how this feature has been implemented in the codebase.
- **Usage Examples**: Practical examples to guide users on how to leverage this feature effectively.
- **Committing with the Generated Message**: Instructions and guidelines on how users can commit with the messages generated using this feature.
By enhancing the `README.md` with this detailed explanation, we aim to provide users with a clear understanding of how to use the `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` feature. This will …

Add Detailed Explanation of OCO_MESSAGE_TEMPLATE_PLACEHOLDER Feature to README.md

---

src/github-action.ts

This Pull Request introduces a significant optimization in our GitHub Action workflow. It aims to address the issue #201 where the action was redundantly rebasing and amending commits, even when there were no changes in the commit messages, thus leading to a loop of triggering workflows unnecessarily.
- 🔧 chore(github-action.ts): add check for changes in commit messages before rebasing to improve efficiency
- 🐛 fix(github-action.ts): fix logic to check if there are any changes in commit messages before rebasing to ensure correct behavior
With this fix, our GitHub Action will become more efficient by avoiding unnecessary operations, and it will no longer create and push unnecessary commits, thereby reducing the number of workflow triggers.
This PR is an important step towards improving the …

Fix #201: Avoid unnecessary rebase in GitHub Action by adding checks for changes in commit messages

---

src/prompts.ts

Nothing much, slightly improved the prompt

chore(prompts.ts): update INIT_MAIN_PROMPT for better instructions

---

README.md
src/commands/config.ts

https://openai.com/blog/new-models-and-developer-products-announced-at-devday

feat: add instructions and support for configuring GPT-4 Turbo (Preview)

---

README.md

docs: update ollama usage readme

---

README.md
out/cli.cjs
out/github-action.cjs
package-lock.json
package.json
src/engine/ollama.ts

Fixes this bug: https://github.com/di-sukharev/opencommit/issues/302

Switch ollama api endpoint from /api/generate to /api/chat

---

README.md

📝 (README.md): add support for custom AI models and update documentatation
missing document for pr #327

Add doc to README.md about OCO_ AI_PROVIDER

---

src/i18n/zh_CN.json

[Issue #372](https://github.com/di-sukharev/opencommit/issues/372)

fix(i18n): zh_CN is wrong

---

out/cli.cjs
out/github-action.cjs
src/commands/config.ts
src/utils/engine.ts

support read OCO_OLLAMA_API_URL from env to OllamaAiEngine and fix bug in getting ollma model name when slash exists

support read endpoint by OCO_OLLAMA_API_URL from env when using ollama

---

out/cli.cjs
out/github-action.cjs
package-lock.json
package.json
src/commands/config.ts
src/engine/anthropic.ts
src/engine/openAi.ts

fixes https://github.com/di-sukharev/opencommit/issues/383

Fix anthropic and openai generation

---

src/i18n/ko.json

fix(i18n): correct typo in Korean translation for 'feat' commit type

---

README.md
src/commands/config.ts
src/engine/aimlapi.ts
src/utils/engine.ts

Hi! From https://github.com/di-sukharev/opencommit/issues/483
Introduces AIMLAPI as a new AI provider option. Updates the README, config validation, model list, and engine selection logic to support AIMLAPI. Implements the AimlApiEngine for handling chat completions via the AIMLAPI endpoint.
Tested, all works just fine:

feat: add AIML API provider support
